addons:
  apt:
    packages:
      - graphviz
branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
  - panda install Pod::To::HTML

script: make test && make html
