addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - graphviz
      - g++-4.8
      - ruby-sass

branches:
  except:
    - gh-pages
notifications:
  irc:
    channels:
    - "irc.freenode.net#perl6"
    on_success: change
    on_failure: always
    template:
      - "Doc build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

language: perl6
sudo: false
perl6:
  - latest
before_install:
  - nvm install 7.2.1
  - nvm use 7.2.1
install:
  - rakudobrew build-zef
  - export PATH="$PATH:/home/travis/.rakudobrew/moar-nom/install/share/perl6/site/bin"
  - zef --force --/test install LWP::Simple
  - zef --depsonly install .
  - zef install Pod::To::HTML

script:
  - make test
  - export CXX=g++-4.8
  - $CXX --version
  - make html
